<a href="https://colab.research.google.com/github/RafaXzaviero/DATAMINING_TUGAS3/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
# Langkah 1: Memuat Data
# Ganti dengan path ke dataset Anda jika menggunakan dataset lain
data = {'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France', 'Spain', 'France', 'Germany', 'France'],
        'Age': [44, 48, 30, 45, 40, 35, 38, 48, 50, 37],
        'Salary': [72000, 48000, 54000, 61000, 58000, 52000, 79000, 83000, 67000, 69000],
        'Purchased': ['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']}
df = pd.DataFrame(data)

display(df)

Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   48   48000       Yes
2  Germany   30   54000        No
3    Spain   45   61000        No
4  Germany   40   58000       Yes
5   France   35   52000       Yes
6    Spain   38   79000        No
7   France   48   83000       Yes
8  Germany   50   67000        No
9   France   37   69000       Yes

In [3]:
# Langkah 2: Menangani Nilai yang Hilang (jika ada)
# Menggunakan SimpleImputer untuk mengisi nilai NaN dengan mean (rata-rata) dari kolom
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Terapkan imputer pada kolom 'Age' dan 'Salary'
# Pastikan kolom yang akan diimputasi adalah numerik
df[['Age', 'Salary']] = imputer.fit_transform(df[['Age', 'Salary']])

display(df)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  48.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  45.0  61000.0        No
4  Germany  40.0  58000.0       Yes
5   France  35.0  52000.0       Yes
6    Spain  38.0  79000.0        No
7   France  48.0  83000.0       Yes
8  Germany  50.0  67000.0        No
9   France  37.0  69000.0       Yes

from matplotlib import pyplot as plt
df['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Salary'].plot(kind='hist', bins=20, title='Salary')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Country').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Purchased').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Age', y='Salary', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['Salary'].plot(kind='line', figsize=(8, 4), title='Salary')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Purchased'].value_counts()
    for x_label, grp in df.groupby('Country')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Country')
_ = plt.ylabel('Purchased')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Country'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Country', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Purchased'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Purchased', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Country'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Salary', y='Country', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Purchased'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Salary', y='Purchased', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [4]:
# Langkah 3: Mengkodekan Data Kategorikal
# One-Hot Encoding untuk kolom 'Country'
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(df))

# Label Encoding untuk kolom 'Purchased' (variabel dependen)
le = LabelEncoder()
y = le.fit_transform(df['Purchased'])

print("Data setelah One-Hot Encoding (X):")
display(X)
print("\nData setelah Label Encoding (y):")
display(y)

Data setelah One-Hot Encoding (X):


array([[1.0, 0.0, 0.0, 44.0, 72000.0, 'No'],
       [0.0, 0.0, 1.0, 48.0, 48000.0, 'Yes'],
       [0.0, 1.0, 0.0, 30.0, 54000.0, 'No'],
       [0.0, 0.0, 1.0, 45.0, 61000.0, 'No'],
       [0.0, 1.0, 0.0, 40.0, 58000.0, 'Yes'],
       [1.0, 0.0, 0.0, 35.0, 52000.0, 'Yes'],
       [0.0, 0.0, 1.0, 38.0, 79000.0, 'No'],
       [1.0, 0.0, 0.0, 48.0, 83000.0, 'Yes'],
       [0.0, 1.0, 0.0, 50.0, 67000.0, 'No'],
       [1.0, 0.0, 0.0, 37.0, 69000.0, 'Yes']], dtype=object)


Data setelah Label Encoding (y):


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [6]:
# Langkah 4: Penskalaan Fitur (Feature Scaling)
# Terapkan StandardScaler pada kolom numerik (kolom Age dan Salary setelah One-Hot Encoding)
# Perhatikan indeks kolom setelah One-Hot Encoding: kolom Age adalah kolom ke-3 dan Salary adalah kolom ke-4
# Jika menggunakan data yang berbeda, pastikan untuk menyesuaikan indeks kolom
scaler = StandardScaler()
X[:, 3:5] = scaler.fit_transform(X[:, 3:5])

print("Data setelah Feature Scaling (X):")
display(X)

Data setelah Feature Scaling (X):


array([[1.0, 0.0, 0.0, 0.40317336795650194, 0.6948224776047048, 'No'],
       [0.0, 0.0, 1.0, 1.0482507566869048, -1.4708579720722974, 'Yes'],
       [0.0, 1.0, 0.0, -1.8545974925999087, -0.9294378596530468, 'No'],
       [0.0, 0.0, 1.0, 0.5644427151391026, -0.2977810618305878, 'No'],
       [0.0, 1.0, 0.0, -0.24190402077390113, -0.5684911180402131, 'Yes'],
       [1.0, 0.0, 0.0, -1.0482507566869048, -1.1099112304594636, 'Yes'],
       [0.0, 0.0, 1.0, -0.5644427151391026, 1.326479275427164, 'No'],
       [1.0, 0.0, 0.0, 1.0482507566869048, 1.6874260170399975, 'Yes'],
       [0.0, 1.0, 0.0, 1.3707894510521064, 0.24363905058866278, 'No'],
       [1.0, 0.0, 0.0, -0.7257120623217034, 0.4241124213950796, 'Yes']],
      dtype=object)

In [7]:
# Langkah 5: Membagi Data menjadi Training Set dan Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print("Bentuk X_train:", X_train.shape)
print("Bentuk X_test:", X_test.shape)
print("Bentuk y_train:", y_train.shape)
print("Bentuk y_test:", y_test.shape)

Bentuk X_train: (8, 6)
Bentuk X_test: (2, 6)
Bentuk y_train: (8,)
Bentuk y_test: (2,)


Variabel X: Ini adalah variabel yang berisi fitur atau variabel independen dari dataset Anda. Setelah melalui tahapan preprocessing:
Kolom kategorikal 'Country' telah diubah menjadi format numerik menggunakan One-Hot Encoding. Ini berarti satu kolom kategorikal 'Country' dipecah menjadi beberapa kolom biner (0 atau 1), masing-masing merepresentasikan salah satu kategori negara (France, Spain, Germany). Ini dilakukan agar algoritma machine learning dapat memprosesnya.
Kolom numerik 'Age' dan 'Salary' telah mengalami Penskalaan Fitur (Feature Scaling) menggunakan StandardScaler. Ini mengubah nilai-nilai pada kolom tersebut sehingga memiliki rata-rata 0 dan standar deviasi 1. Penskalaan ini membantu mencegah fitur dengan nilai yang lebih besar mendominasi algoritma machine learning.
Kolom asli 'Purchased' (sebelum di-encode menjadi y) juga masih ada di sini karena kita menggunakan remainder='passthrough' di ColumnTransformer, namun biasanya kolom target ini akan dipisahkan sebelum penskalaan fitur. Dalam konteks machine learning, X akan digunakan sebagai input untuk melatih model.
Variabel y: Ini adalah variabel yang berisi target atau variabel dependen dari dataset Anda. Kolom 'Purchased' yang awalnya berisi nilai kategorikal ('Yes' dan 'No') telah diubah menjadi nilai numerik biner (0 dan 1) menggunakan Label Encoding. Ini adalah format yang dibutuhkan oleh sebagian besar algoritma machine learning untuk variabel target dalam tugas klasifikasi. Dalam konteks machine learning, y adalah apa yang ingin diprediksi oleh model berdasarkan fitur-fitur di X.
Singkatnya, X adalah data input yang sudah diproses dan diskalakan untuk model, sementara y adalah output target yang sudah diubah menjadi format numerik.